### ISSUE TITLE
Error: Type 'ImageDecoderCallback' not found. During build

### ISSUE THREAD

**Issue by erickim20** [Firelands128/photo_gallery#60]
```
Failed to build iOS app
Error (Xcode): ../../../../../../.pub-cache/hosted/pub.dev/photo_gallery-2.0.1/lib/src/image_providers/album_thumbnail_provider.dart:29:35: Error: Type 'ImageDecoderCallback' not found.
album_thumbnail_provider.dart:29
Could not build the application for the simulator.
Error launching application on iPhone 14.
```

**Comment by latygin** [comment]
I have the same problem on version 2.0.1

**Comment by Firelands128** [comment]
If you can update your flutter to the latest version, it should be fixed. If it's still there, feel free to reopen the issue.

**Comment by latygin** [comment]
Maybe you should update the flutter version constraint in pubspec.yaml?

**Comment by SreehariRajeevFSS** [comment]
We are still facing this issue, cannot update flutter version.
